# Generated by Django 3.2.5 on 2021-07-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuserauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Document',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Parrent',
            new_name='parrent',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Regdno',
            new_name='regdno',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Rollno',
            new_name='rollno',
        ),
    ]
